#TODO: Single startup script work in progress

services:
  backend:
    build:
      context: .
      target: python-base
    command: ./start_backend.sh
    ports:
      - "8000:8000"  # API port
      - "4040:4040"  # ngrok web UI port
    env_file:
      - .env

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Serve production build
    depends_on:
      - backend
