#TODO: Single startup script work in progress

services:
  app:
    build:
      context: .
      target: python-base
    command: python alphasignal/app.py
    ports:
      - "8000:8000"
    environment:
      - HOST=127.0.0.1
    depends_on:
      - processor

  processor:
    build:
      context: .
      target: python-base
    command: python alphasignal/processor.py
    environment:
      - SOME_PROCESSOR_ENV=value

  ngrok:
    build:
      context: .
      target: python-base
    command: python alphasignal/ngrok_run.py
    ports:
      - "4040:4040"  # ngrok web UI
    environment:
      - API_URL=http://app:8000

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "5173:5173"

