[project]
name = "alphasignal"
version = "0.1.0"
description = "One stop shop for the Alpha Singal."
authors = []
license = "MIT"
readme = "README.md"
requires-python = "3.13.1"
dependencies = [
    "solana (==0.36.2)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
